[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers.docker]
  exposedByDefault = false

[certificatesResolvers.myresolver.acme]
  email = "your.email@example.com"
  [certificatesResolvers.myresolver.acme.tlsChallenge]
